PROGRAM FORCAARMADA;

VAR

 NOME,SEXO:STRING;
 SEXO_M,SEXO_F,APTO,INAPTO:INTEGER;
 IDADE,VEZES,CONT:INTEGER;

BEGIN
 WRITELN ('INFORME QUANTOS CANDIDATOS SERAO CADASTRADOS PARA SELECAO.');
 READLN (VEZES);

 FOR CONT:= 1 TO VEZES DO
  BEGIN
   WRITELN ('DIGITE O NOME DO CANDITADO');
   READLN (NOME);
   WRITELN ('DIGITE O SEXO DO CANDITADO');
   READLN (SEXO);
   WRITELN ('DIGITE A IDADE DO CANDITADO');
   READLN (IDADE);

   IF IDADE > 18 THEN
    APTO:= APTO+1
    ELSE
     INAPTO:= INAPTO+1;
   IF SEXO = 'MASCULINO' THEN
    SEXO_M:= SEXO_M + 1
    ELSE
     SEXO_F:= SEXO_F + 1;
  END;

  WRITELN ('FORAM APTOS PARA SELECAO ',APTO,' ENQUANTO ',INAPTO,' PERMANECERAM INAPTOS');
  WRITELN (SEXO_M,' FORAM O NUMERO DE HOMENS INSCRITOS');
  WRITELN (SEXO_F,' FORAM O NUMERO DE MULHERES INSCRITAS');

END.

